version: "3.2"

services:
#Mysql Container
  mysql:
    image: mysql:5.7.23
    container_name: mysql
    hostname: mysql
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - ./mysql.env
    restart: always

<<<<<<< HEAD
#Mediawiki Container
  mediawiki:
    image: diouxx/mediawiki
    container_name : wiki
    hostname: wiki
    ports:
      - "80:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/www/html/wiki/:/var/www/html/wiki
    restart: always
=======
#Mediawiki Persistance data
wiki-data:
  image: busybox
  container_name: wiki-data
  volumes:
    - /var/www/html/wiki:/var/www/html/wiki

#Mediawiki container
wiki:
  image: diouxx/mediawiki
  container_name: wiki
  hostname: wiki
  ports:
    - 80:80
  links:
    - mysql:mysql
  volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - wiki-data
>>>>>>> 82919cc15dc686f28bfa05c478afc3381389a959
